// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/crearmascota": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Crea el registro de una mascota con los datos introducidos",
                "operationId": "create-pet",
                "parameters": [
                    {
                        "description": "nombre,especie,genero,edad,fecha de nacimiento",
                        "name": "pet",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.Pet"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Pet"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "not"
                        }
                    }
                }
            }
        },
        "/kpidemascotas": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Obtiene los datos de kpi mascota",
                "operationId": "get-kpi-pet",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.KpiMascota"
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "not"
                        }
                    }
                }
            }
        },
        "/lismascotas": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Obtiene el listado de mascotas",
                "operationId": "get-list-pet",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.Pet"
                            }
                        }
                    },
                    "405": {
                        "description": "Method Not Allowed",
                        "schema": {
                            "type": "not"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.KpiMascota": {
            "type": "object",
            "properties": {
                "desviación estándar edad perro": {
                    "description": "Desviación estándar de las edades de las mascotas",
                    "type": "number"
                },
                "edad promedio perro": {
                    "description": "Edad promedio de mis mascotas",
                    "type": "string"
                },
                "especie mas numerosa": {
                    "description": "Especie más numerosa",
                    "type": "string"
                }
            }
        },
        "main.Pet": {
            "type": "object",
            "properties": {
                "edad": {
                    "description": "Edad de la mascota",
                    "type": "integer"
                },
                "especie": {
                    "description": "Especie de la mascota",
                    "type": "string"
                },
                "fecha nacimiento": {
                    "description": "Fecha de nacimiento de la mascota",
                    "type": "string"
                },
                "genero": {
                    "description": "Genero de la mascota",
                    "type": "string"
                },
                "nombre": {
                    "description": "Nombre de la mascota",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8022",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API - Mascota\"",
	Description:      "Microservicio con 3 endpoints:",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
